import { Document, Packer, Paragraph, TextRun } from 'docx';
import { PDFDocument, StandardFonts } from 'pdf-lib';

// Minimal document generation
export const generatePolicyDocument = async (companyName: string) => {
  // Create simple DOCX
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph(new TextRun(`Compliance Policy for ${companyName}`)),
        new Paragraph(new TextRun('Generated by Fairform'))
      ]
    }]
  });
  const docxBuffer = await Packer.toBuffer(doc);

  // Create simple PDF
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage();
  page.drawText(`Compliance Policy for ${companyName}`, {
    x: 50,
    y: 700,
    size: 15,
    font: await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  });
  const pdfBuffer = Buffer.from(await pdfDoc.save());

  return { docxBuffer, pdfBuffer };
};
